// template-repo/templates/fastapi-nextjs-mysql/frontend/app/page.tsx
"use client";

import { FormEvent, useEffect, useState } from "react";

type User = {
  id: number;
  name: string;
  email: string;
  created_at: string;
};

export default function HomePage() {
  const [users, setUsers] = useState<User[]>([]);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  async function loadUsers() {
    setLoading(true);
    setError("");
    try {
      const response = await fetch("/api/users", { cache: "no-store" });
      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.detail ?? "Failed to load users");
      }
      setUsers(payload);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Failed to load users");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadUsers();
  }, []);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmitting(true);
    setError("");
    try {
      const response = await fetch("/api/users", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ name, email })
      });
      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.detail ?? "Failed to create user");
      }
      setUsers((current) => [payload, ...current]);
      setName("");
      setEmail("");
    } catch (submitError) {
      setError(submitError instanceof Error ? submitError.message : "Failed to create user");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <main className="page">
      <section className="hero">
        <p className="eyebrow">Template Repo v1</p>
        <h1>__DISPLAY_NAME__</h1>
        <p>
          FastAPI handles the API and persistence layer, while Next.js powers a
          modern React frontend. Use this as a direct starting point for admin
          tools, dashboards, and internal platforms.
        </p>
      </section>

      <section className="grid">
        <article className="panel">
          <h2>User List</h2>
          <div className="metric">Total {users.length} users</div>
          {loading ? <p className="muted">Loading users...</p> : null}
          {!loading && users.length === 0 ? (
            <p className="muted">The API is connected, but no user records are available yet.</p>
          ) : null}
          <ul className="user-list">
            {users.map((user) => (
              <li className="user-item" key={user.id}>
                <div>
                  <strong>{user.name}</strong>
                  <div className="muted">{user.email}</div>
                </div>
                <span className="badge">READY</span>
              </li>
            ))}
          </ul>
        </article>

        <article className="panel">
          <h2>Create User</h2>
          <form className="form" onSubmit={handleSubmit}>
            <div className="field">
              <label htmlFor="name">Name</label>
              <input
                id="name"
                value={name}
                onChange={(event) => setName(event.target.value)}
                placeholder="Template Admin"
                required
              />
            </div>
            <div className="field">
              <label htmlFor="email">Email</label>
              <input
                id="email"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                placeholder="admin@example.com"
                required
              />
            </div>
            <button className="button" disabled={submitting} type="submit">
              {submitting ? "Submitting..." : "Create User"}
            </button>
            {error ? <p className="error">{error}</p> : null}
          </form>
        </article>
      </section>
    </main>
  );
}

// template-repo/templates/fastapi-vue3-mysql/frontend/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { createUser, fetchHealth, fetchUsers, type HealthResponse, type User } from './api'

const health = ref<HealthResponse | null>(null)
const users = ref<User[]>([])
const loading = ref(false)
const submitting = ref(false)
const errorMessage = ref('')

const form = ref({
  name: '',
  email: ''
})

async function loadDashboard() {
  loading.value = true
  errorMessage.value = ''
  try {
    const [healthResult, userResult] = await Promise.all([fetchHealth(), fetchUsers()])
    health.value = healthResult
    users.value = userResult
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : '加载失败'
  } finally {
    loading.value = false
  }
}

async function handleSubmit() {
  submitting.value = true
  errorMessage.value = ''
  try {
    await createUser(form.value)
    form.value = { name: '', email: '' }
    await loadDashboard()
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : '提交失败'
  } finally {
    submitting.value = false
  }
}

onMounted(loadDashboard)
</script>

<template>
  <main class="page">
    <section class="hero">
      <p class="eyebrow">Template Repo v1</p>
      <h1>__DISPLAY_NAME__</h1>
      <p class="subtitle">FastAPI + Vue 3 + MySQL 可运行模板</p>
    </section>

    <section class="grid">
      <article class="panel">
        <h2>服务状态</h2>
        <p v-if="loading">正在连接后端...</p>
        <div v-else-if="health" class="status">
          <strong>{{ health.status }}</strong>
          <span>{{ health.service }}</span>
          <small>{{ health.databaseUrl }}</small>
        </div>
        <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
      </article>

      <article class="panel">
        <h2>新增用户</h2>
        <form class="form" @submit.prevent="handleSubmit">
          <input v-model="form.name" type="text" placeholder="姓名" required maxlength="64" />
          <input v-model="form.email" type="email" placeholder="邮箱" required maxlength="128" />
          <button :disabled="submitting" type="submit">
            {{ submitting ? '提交中...' : '创建用户' }}
          </button>
        </form>
      </article>
    </section>

    <section class="panel">
      <div class="section-title">
        <h2>用户列表示例</h2>
        <button class="secondary" @click="loadDashboard">刷新</button>
      </div>

      <ul v-if="users.length" class="list">
        <li v-for="user in users" :key="user.id">
          <strong>{{ user.name }}</strong>
          <span>{{ user.email }}</span>
        </li>
      </ul>
      <p v-else class="empty">当前还没有用户数据</p>
    </section>
  </main>
</template>
